"""Bounded FFmpeg audio chunks with source-relative offsets."""

import logging
import subprocess
import tempfile
from pathlib import Path
from typing import Any, TypedDict

from app.core.app_config import APP_CONFIG

logger = logging.getLogger(__name__)

CHUNK_LENGTH_MS = APP_CONFIG.transcription.chunk_seconds * 1000
OVERLAP_MS = APP_CONFIG.transcription.overlap_seconds * 1000


class ChunkInfo(TypedDict):
    path: Path
    start_offset_ms: int
    duration_ms: int
    is_temp: bool


def split_audio(
    file_path: Path,
    meeting_id: str,
    chunk_length_ms: int = CHUNK_LENGTH_MS,
    overlap_ms: int = OVERLAP_MS,
) -> list[ChunkInfo]:
    """Split without loading the entire recording into Python memory."""
    if not file_path.is_file():
        raise FileNotFoundError(f"Audio file not found at: {file_path}")
    if chunk_length_ms <= 0 or not 0 <= overlap_ms < chunk_length_ms:
        raise ValueError("Invalid audio chunk length or overlap")

    try:
        probe = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", str(file_path)],
            capture_output=True, text=True, check=True,
        )
        total_ms = int(float(probe.stdout.strip()) * 1000)
    except (OSError, subprocess.CalledProcessError, ValueError) as exc:
        raise RuntimeError(f"Could not inspect audio duration for meeting {meeting_id}") from exc
    if total_ms <= 0:
        raise ValueError("Audio recording has no duration")
    if total_ms <= chunk_length_ms:
        return [ChunkInfo(path=file_path, start_offset_ms=0, duration_ms=total_ms, is_temp=False)]

    logger.info("Splitting %.1f-minute recording into %d-second chunks meeting=%s",
                total_ms / 60000.0, chunk_length_ms // 1000, meeting_id)
    chunk_dir = Path(tempfile.mkdtemp(prefix="meetpilot_chunks_"))
    chunks: list[ChunkInfo] = []
    try:
        start_ms = 0
        while start_ms < total_ms:
            end_ms = min(start_ms + chunk_length_ms, total_ms)
            path = chunk_dir / f"chunk_{len(chunks):04d}.wav"
            subprocess.run(
                ["ffmpeg", "-nostdin", "-hide_banner", "-loglevel", "error",
                 "-ss", f"{start_ms / 1000:.3f}", "-i", str(file_path),
                 "-t", f"{(end_ms - start_ms) / 1000:.3f}", "-vn",
                 "-ac", "1", "-ar", "16000", "-c:a", "pcm_s16le", str(path)],
                capture_output=True, text=True, check=True,
            )
            if not path.is_file() or path.stat().st_size == 0:
                raise RuntimeError(f"FFmpeg produced an empty chunk for meeting {meeting_id}")
            chunks.append(ChunkInfo(path=path, start_offset_ms=start_ms,
                                    duration_ms=end_ms - start_ms, is_temp=True))
            if end_ms == total_ms:
                break
            start_ms = end_ms - overlap_ms
        return chunks
    except (OSError, subprocess.CalledProcessError, RuntimeError) as exc:
        cleanup_temp_chunks(chunks)
        for path in chunk_dir.glob("chunk_*.wav"):
            path.unlink(missing_ok=True)
        if chunk_dir.exists():
            chunk_dir.rmdir()
        raise RuntimeError(f"Could not split audio for meeting {meeting_id}") from exc


def dedupe_overlap_segments(segments: list[dict[str, Any]], overlap_seconds: float = 15.0) -> list[dict[str, Any]]:
    """Drop repeated transcript turns from overlapping chunks."""
    if not segments:
        return []
    sorted_segments = sorted(segments, key=lambda s: s.get("start_time", 0.0))
    deduped: list[dict[str, Any]] = []
    for seg in sorted_segments:
        if deduped:
            prev_end = deduped[-1].get("end_time", 0.0)
            if seg.get("start_time", 0.0) < (prev_end - (overlap_seconds / 2.0)):
                continue
        deduped.append(seg)
    return deduped


def cleanup_temp_chunks(chunks: list[ChunkInfo]) -> None:
    """Remove only files and directories generated by split_audio."""
    directories: set[Path] = set()
    for chunk in chunks:
        if chunk["is_temp"]:
            path = chunk["path"]
            directories.add(path.parent)
            try:
                path.unlink(missing_ok=True)
            except OSError:
                logger.warning("Could not remove temporary chunk %s", path)
    for directory in directories:
        if directory.name.startswith("meetpilot_chunks_"):
            try:
                directory.rmdir()
            except OSError:
                logger.warning("Could not remove temporary chunk directory %s", directory)
